HOME_DIR = "C:/Users/Eddie/Documents/Thesis Code/thesis_flat_earth"
TFES_FP = "C:/Users/Eddie/Documents/Thesis Code/fe_data/tfes_forum_anon.db"
TFES_TOK_FP = "C:/Users/Eddie/Documents/Thesis Code/fe_data/tfes_posts_anon.json"
REDDIT_DIR = "C:/Users/Eddie/Documents/Thesis Code/fe_data/Reddit"
FE_REDDIT_DIR = "C:/Users/Eddie/Documents/Thesis Code/fe_data/Reddit/FE"
OT_REDDIT_DIR = "C:/Users/Eddie/Documents/Thesis Code/fe_data/Reddit/OT"
SCIENCE_W2V_FP = "C:/Users/Eddie/Documents/Datasets/Models/science_w2v.model"